"use client";
import { ChangeEvent, useEffect, useState } from "react";
import { analyze, answerQuestion, formatMoney, formatPercent } from "../lib/analysis";
import { parseSummary, parseTransactions } from "../lib/csv";
import { applyMemory } from "../lib/memory";
import { Analysis, MemoryFact, SummaryRow, Transaction } from "../lib/types";
import type { AiAnalysisReport } from "../lib/ai-analysis";

type FileState = { name: string; text: string } | null;
const demoAssets = ["period-a-summary.csv", "period-b-summary.csv", "period-a-transactions.csv", "period-b-transactions.csv"] as const;

export default function LedgerLens() {
  const [summaryA, setSummaryA] = useState<FileState>(null); const [summaryB, setSummaryB] = useState<FileState>(null); const [transactionsA, setTransactionsA] = useState<FileState>(null); const [transactionsB, setTransactionsB] = useState<FileState>(null);
  const [analysis, setAnalysis] = useState<Analysis | null>(null); const [error, setError] = useState(""); const [selected, setSelected] = useState<number | null>(null); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [vendor, setVendor] = useState("Amazon Web Services"); const [category, setCategory] = useState("Infrastructure"); const [memoryMessage, setMemoryMessage] = useState(""); const [memories, setMemories] = useState<MemoryFact[]>([]); const [aiReport, setAiReport] = useState<AiAnalysisReport | null>(null); const [aiError, setAiError] = useState(""); const [aiLoading, setAiLoading] = useState(false); const [analysisSessionId, setAnalysisSessionId] = useState<string | null>(null);
  const pick = (setter: (state: FileState) => void) => async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) setter({ name: file.name, text: await file.text() }); };
  const loadMemories = async (subjects: string[] = []) => { const response = await fetch(`/api/memory${subjects.length ? `?subjects=${encodeURIComponent(subjects.join(","))}` : ""}`); const body = await response.json() as { memories?: MemoryFact[]; error?: string }; if (!response.ok || !body.memories) throw new Error(body.error ?? "Unable to load Supabase Business Memory."); setMemories(body.memories); return body.memories; };
  useEffect(() => { loadMemories().catch(error => setMemoryMessage(error instanceof Error ? error.message : "Unable to load Supabase Business Memory.")); }, []);
  const analyzeFiles = async (aSummary: NonNullable<FileState>, bSummary: NonNullable<FileState>, aTx: NonNullable<FileState>, bTx: NonNullable<FileState>) => { const summariesA: SummaryRow[] = parseSummary(aSummary.text, aSummary.name); const summariesB: SummaryRow[] = parseSummary(bSummary.text, bSummary.name); const raw: Transaction[] = [...parseTransactions(aTx.text, aTx.name, "A"), ...parseTransactions(bTx.text, bTx.name, "B")]; let freshMemories: MemoryFact[] = []; try { freshMemories = await loadMemories(raw.map(transaction => transaction.counterparty)); } catch (caught) { setMemoryMessage(caught instanceof Error ? caught.message : "Supabase Business Memory is unavailable for this analysis."); } setAnalysis(analyze(summariesA, summariesB, applyMemory(raw, freshMemories), freshMemories)); setAnalysisSessionId(crypto.randomUUID()); setAiReport(null); setSelected(null); setAnswer(""); };
  const run = async () => { try { setError(""); if (!summaryA || !summaryB || !transactionsA || !transactionsB) throw new Error("Upload both period summaries and both period transaction CSVs, or use the demo data."); await analyzeFiles(summaryA, summaryB, transactionsA, transactionsB); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not analyze these files."); } };
  const loadDemo = async () => { try { setError(""); const loaded = await Promise.all(demoAssets.map(async name => { const response = await fetch(`/demo-data/${name}`); if (!response.ok) throw new Error(`Could not load ${name}.`); return { name, text: await response.text() }; })); const [aSummary, bSummary, aTx, bTx] = loaded; setSummaryA(aSummary); setSummaryB(bSummary); setTransactionsA(aTx); setTransactionsB(bTx); await analyzeFiles(aSummary, bSummary, aTx, bTx); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load demo data."); } };
  const teach = async () => { if (!vendor.trim() || !category.trim()) return; try { const response = await fetch("/api/memory", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "vendor_classification", subject: vendor, fact: `Classify as ${category}`, source: "user_confirmed" }) }); const body = await response.json() as { memory?: MemoryFact; error?: string }; if (!response.ok || !body.memory) throw new Error(body.error ?? "Unable to save Supabase Business Memory."); setMemories(current => [...current.filter(memory => memory.id !== body.memory?.id), body.memory!]); setMemoryMessage(`Saved to Supabase: ${body.memory.subject} will be classified as ${category} in future analyses.`); } catch (caught) { setMemoryMessage(caught instanceof Error ? caught.message : "Unable to save Supabase Business Memory."); } };
  const generateInterpretation = async () => { if (!analysis) return; const sessionId = analysisSessionId ?? crypto.randomUUID(); if (!analysisSessionId) setAnalysisSessionId(sessionId); setAiError(""); setAiLoading(true); try { const response = await fetch("/api/interpret", { method: "POST", headers: { "Content-Type": "application/json", "x-ledgerlens-session": sessionId }, body: JSON.stringify({ analysis }) }); const body = await response.json() as { report?: AiAnalysisReport; error?: string }; if (!response.ok || !body.report) throw new Error(body.error ?? "No validated analysis was returned."); setAiReport(body.report); } catch (caught) { setAiReport(null); setAiError(caught instanceof Error ? caught.message : "Unable to generate interpretation."); } finally { setAiLoading(false); } };
  return <div className="shell"><header><div><p className="eyebrow">LEDGERLENS</p><h1>Understand what changed. <em>And why.</em></h1></div><span className="status">Evidence-first financial investigation</span></header>
    {!analysis && <section className="hero"><div><h2>Compare two periods with transaction-level proof.</h2><p>LedgerLens calculates the variance in code, ranks material changes, then connects each claim to the uploaded rows.</p><p className="muted">Synthetic files: <a href="/demo-data/period-a-summary.csv" download>June summary</a>, <a href="/demo-data/period-a-transactions.csv" download>June transactions</a>, <a href="/demo-data/period-b-summary.csv" download>July summary</a>, <a href="/demo-data/period-b-transactions.csv" download>July transactions</a>.</p></div><button className="secondary" onClick={loadDemo}>Use demo data</button></section>}
    <section className="upload"><h2>1. Upload financial data</h2><p className="muted">Required: two summaries and transaction detail for each period. CSV only.</p><div className="file-grid"><Upload label="Period A summary" file={summaryA} onChange={pick(setSummaryA)} /><Upload label="Period B summary" file={summaryB} onChange={pick(setSummaryB)} /><Upload label="Period A transactions" file={transactionsA} onChange={pick(setTransactionsA)} /><Upload label="Period B transactions" file={transactionsB} onChange={pick(setTransactionsB)} /></div><button onClick={() => run()}>Analyze changes <span>→</span></button>{error && <p className="error">{error}</p>}</section>
    {analysis && <Dashboard analysis={analysis} selected={selected} setSelected={setSelected} question={question} setQuestion={setQuestion} answer={answer} ask={() => setAnswer(answerQuestion(question, analysis))} vendor={vendor} setVendor={setVendor} category={category} setCategory={setCategory} teach={teach} memoryMessage={memoryMessage} aiReport={aiReport} aiError={aiError} aiLoading={aiLoading} generateInterpretation={generateInterpretation} />}
  </div>;
}
function Upload({ label, file, onChange }: { label: string; file: FileState; onChange: (event: ChangeEvent<HTMLInputElement>) => void }) { return <label className="file"><span>{label}</span><strong>{file?.name ?? "Choose CSV"}</strong><input type="file" accept=".csv,text/csv" onChange={onChange} /></label>; }
function Dashboard(props: { analysis: Analysis; selected: number | null; setSelected: (value: number | null) => void; question: string; setQuestion: (value: string) => void; answer: string; ask: () => void; vendor: string; setVendor: (value: string) => void; category: string; setCategory: (value: string) => void; teach: () => void; memoryMessage: string; aiReport: AiAnalysisReport | null; aiError: string; aiLoading: boolean; generateInterpretation: () => void }) { const { analysis } = props; const selected = props.selected === null ? null : analysis.insights[props.selected]; const insightFor = (changeId: string) => analysis.insights[Number(changeId.replace("change-", "")) - 1]; return <section className="dashboard"><div className="summary"><p className="eyebrow">EXECUTIVE SUMMARY</p><h2>{props.aiReport?.executiveSummary ?? analysis.summary}</h2><button className="ai-button" onClick={props.generateInterpretation} disabled={props.aiLoading}>{props.aiLoading ? "Generating grounded analysis…" : "Generate AI interpretation"}</button>{props.aiError && <p className="ai-error">{props.aiError}</p>}<div className="metrics"><Metric label="Revenue" a={analysis.totals.revenueA} b={analysis.totals.revenueB} /><Metric label="Expenses" a={analysis.totals.expenseA} b={analysis.totals.expenseB} /><Metric label="Net result" a={analysis.totals.periodA} b={analysis.totals.periodB} /></div></div>
  {props.aiReport && <section className="ai-results"><p className="eyebrow">AI-EXPLAINED KEY CHANGES</p>{props.aiReport.keyChanges.map(change => { const insight = insightFor(change.changeId); return <button className="ai-change" key={change.changeId} onClick={() => insight && props.setSelected(analysis.insights.indexOf(insight))}><span>{change.confidence.replace("_", " ")}</span><strong>{change.title}</strong><p>{change.explanation}</p>{insight && <small>{insight.variance.change >= 0 ? "+" : "−"}{formatMoney(Math.abs(insight.variance.change))} · {formatPercent(insight.variance.percentChange)} · View evidence</small>}</button>; })}{props.aiReport.drivers.length > 0 && <div className="ai-drivers"><strong>Deterministic drivers</strong>{props.aiReport.drivers.flatMap(driver => (insightFor(driver.changeId)?.drivers ?? []).map(item => <p key={`${driver.changeId}-${item.counterparty}`}>{item.counterparty}: {item.change >= 0 ? "+" : "−"}{formatMoney(Math.abs(item.change))} · {Math.abs(item.contributionPercent).toFixed(0)}% of change</p>))}</div>}{props.aiReport.needsContext.map(item => <p className="needs-context" key={item.topic}><strong>Needs context — {item.topic}:</strong> {item.question}</p>)}</section>}
  {analysis.appliedMemories.length > 0 && <p className="memory-used">Memory applied: {analysis.appliedMemories.map(m => `${m.subject} → ${m.fact.replace("Classify as ", "")}`).join(", ")}.</p>}
  <div className="columns"><section><p className="eyebrow">BIGGEST CHANGES</p><div className="cards">{analysis.insights.map((insight, index) => <button className="card" key={insight.variance.category} onClick={() => props.setSelected(index)}><span>{insight.variance.category}</span><strong className={insight.variance.change >= 0 ? "positive" : "negative"}>{insight.variance.change >= 0 ? "+" : "−"}{formatMoney(Math.abs(insight.variance.change))}</strong><small>{formatPercent(insight.variance.percentChange)} · View evidence</small></button>)}</div></section>
  <section className="chat"><p className="eyebrow">ASK LEDGERLENS</p><h3>Grounded in this analysis</h3><div className="chips"><button onClick={() => props.setQuestion("Why did revenue increase?")}>Why did revenue increase?</button><button onClick={() => props.setQuestion("What is driving higher expenses?")}>What is driving higher expenses?</button></div><textarea value={props.question} onChange={e => props.setQuestion(e.target.value)} placeholder="Ask about these financial changes" /><button onClick={props.ask} disabled={!props.question.trim()}>Ask →</button>{props.answer && <p className="answer">{props.answer}</p>}</section></div>
  <section className="teach"><div><p className="eyebrow">TEACH LEDGERLENS</p><h3>Save business context for the next run</h3></div><input value={props.vendor} onChange={e => props.setVendor(e.target.value)} aria-label="Vendor" /><span>belongs under</span><input value={props.category} onChange={e => props.setCategory(e.target.value)} aria-label="Category" /><button onClick={props.teach}>Remember</button>{props.memoryMessage && <p>{props.memoryMessage}</p>}</section>
  {selected && <aside className="evidence"><button className="close" onClick={() => props.setSelected(null)}>×</button><p className="eyebrow">EVIDENCE · {selected.confidence} CONFIDENCE</p><h2>{selected.variance.category} changed {selected.variance.change >= 0 ? "+" : "−"}{formatMoney(Math.abs(selected.variance.change))}</h2><p>Period A: {formatMoney(selected.variance.periodA)} · Period B: {formatMoney(selected.variance.periodB)}</p><h3>Primary drivers</h3>{selected.drivers.map(driver => <div className="driver" key={driver.counterparty}><strong>{driver.counterparty}</strong><span>{driver.change >= 0 ? "+" : "−"}{formatMoney(Math.abs(driver.change))} · {Math.abs(driver.contributionPercent).toFixed(0)}% of change</span>{driver.transactions.map(t => <small key={t.transactionId}>{t.date} · {t.description || t.counterparty} · {formatMoney(t.amount)} · {t.sourceFile}, row {t.sourceRow}</small>)}</div>)}{!selected.drivers.length && <p>No matching transaction detail was found; this variance comes from the uploaded summary.</p>}</aside>}
  </section>; }
function Metric({ label, a, b }: { label: string; a: number; b: number }) { const change = b - a; return <div><span>{label}</span><strong>{formatMoney(b)}</strong><small className={change >= 0 ? "positive" : "negative"}>{change >= 0 ? "+" : "−"}{formatMoney(Math.abs(change))}</small></div>; }
