"use client";
import { ChangeEvent, useState } from "react";
import { analyze, answerQuestion, formatMoney, formatPercent } from "../lib/analysis";
import { parseSummary, parseTransactions } from "../lib/csv";
import { applyMemory, readMemory, saveVendorClassification } from "../lib/memory";
import { Analysis, SummaryRow, Transaction } from "../lib/types";

type FileState = { name: string; text: string } | null;
const demoA = `Date,Description,Amount,Category,Counterparty\n2026-06-01,Acme platform fee,50000,Enterprise Revenue,Acme Corp\n2026-06-02,Globex subscription,30000,Enterprise Revenue,Globex\n2026-06-03,SMB subscriptions,70000,SMB Revenue,Various SMB\n2026-06-05,AWS cloud,-12000,Software,Amazon Web Services\n2026-06-06,Agency retainers,-18000,Marketing,Northstar Agency\n2026-06-07,Engineering contractors,-30000,Contractors,BuildCo`;
const demoB = `Date,Description,Amount,Category,Counterparty\n2026-07-01,Acme platform fee,81200,Enterprise Revenue,Acme Corp\n2026-07-02,Globex subscription,44700,Enterprise Revenue,Globex\n2026-07-03,SMB subscriptions,58300,SMB Revenue,Various SMB\n2026-07-05,AWS cloud,-33400,Software,Amazon Web Services\n2026-07-06,Agency retainers,-27000,Marketing,Northstar Agency\n2026-07-07,Engineering contractors,-12400,Contractors,BuildCo`;
const demoSummaryA = "Category,Amount\nEnterprise Revenue,80000\nSMB Revenue,70000\nSoftware,12000\nMarketing,18000\nContractors,30000";
const demoSummaryB = "Category,Amount\nEnterprise Revenue,125900\nSMB Revenue,58300\nSoftware,33400\nMarketing,27000\nContractors,12400";

export default function LedgerLens() {
  const [summaryA, setSummaryA] = useState<FileState>(null); const [summaryB, setSummaryB] = useState<FileState>(null); const [transactionsA, setTransactionsA] = useState<FileState>(null); const [transactionsB, setTransactionsB] = useState<FileState>(null);
  const [analysis, setAnalysis] = useState<Analysis | null>(null); const [error, setError] = useState(""); const [selected, setSelected] = useState<number | null>(null); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [vendor, setVendor] = useState("Amazon Web Services"); const [category, setCategory] = useState("Infrastructure"); const [memoryMessage, setMemoryMessage] = useState(""); const [aiSummary, setAiSummary] = useState(""); const [aiError, setAiError] = useState("");
  const pick = (setter: (state: FileState) => void) => async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) setter({ name: file.name, text: await file.text() }); };
  const run = (demo = false) => { try { setError(""); const aSummary = demo ? { name: "june-summary.csv", text: demoSummaryA } : summaryA; const bSummary = demo ? { name: "july-summary.csv", text: demoSummaryB } : summaryB; const aTx = demo ? { name: "june-transactions.csv", text: demoA } : transactionsA; const bTx = demo ? { name: "july-transactions.csv", text: demoB } : transactionsB; if (!aSummary || !bSummary || !aTx || !bTx) throw new Error("Upload both period summaries and both period transaction CSVs, or load the demo data."); const summariesA: SummaryRow[] = parseSummary(aSummary.text, aSummary.name); const summariesB: SummaryRow[] = parseSummary(bSummary.text, bSummary.name); const raw: Transaction[] = [...parseTransactions(aTx.text, aTx.name, "A"), ...parseTransactions(bTx.text, bTx.name, "B")]; setAnalysis(analyze(summariesA, summariesB, applyMemory(raw, readMemory()), readMemory())); setSelected(null); setAnswer(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not analyze these files."); } };
  const teach = () => { if (!vendor.trim() || !category.trim()) return; saveVendorClassification(vendor, category); setMemoryMessage(`Saved locally: ${vendor} will be classified as ${category} in future analyses. Run the analysis again to apply it.`); };
  const generateInterpretation = async () => { if (!analysis) return; setAiError(""); setAiSummary("Generating a grounded interpretation…"); try { const response = await fetch("/api/interpret", { method: "POST", headers: { "Content-Type": "application/json", "x-ledgerlens-session": crypto.randomUUID() }, body: JSON.stringify({ analysis }) }); const body = await response.json() as { text?: string; error?: string }; if (!response.ok) throw new Error(body.error); setAiSummary(body.text ?? "No interpretation returned."); } catch (caught) { setAiSummary(""); setAiError(caught instanceof Error ? caught.message : "Unable to generate interpretation."); } };
  return <div className="shell"><header><div><p className="eyebrow">LEDGERLENS</p><h1>Understand what changed. <em>And why.</em></h1></div><span className="status">Evidence-first financial investigation</span></header>
    {!analysis && <section className="hero"><div><h2>Compare two periods with transaction-level proof.</h2><p>LedgerLens calculates the variance in code, ranks material changes, then connects each claim to the uploaded rows.</p></div><button className="secondary" onClick={() => run(true)}>Load demo data</button></section>}
    <section className="upload"><h2>1. Upload financial data</h2><p className="muted">Required: two summaries and transaction detail for each period. CSV only.</p><div className="file-grid"><Upload label="Period A summary" file={summaryA} onChange={pick(setSummaryA)} /><Upload label="Period B summary" file={summaryB} onChange={pick(setSummaryB)} /><Upload label="Period A transactions" file={transactionsA} onChange={pick(setTransactionsA)} /><Upload label="Period B transactions" file={transactionsB} onChange={pick(setTransactionsB)} /></div><button onClick={() => run()}>Analyze changes <span>→</span></button>{error && <p className="error">{error}</p>}</section>
    {analysis && <Dashboard analysis={analysis} selected={selected} setSelected={setSelected} question={question} setQuestion={setQuestion} answer={answer} ask={() => setAnswer(answerQuestion(question, analysis))} vendor={vendor} setVendor={setVendor} category={category} setCategory={setCategory} teach={teach} memoryMessage={memoryMessage} aiSummary={aiSummary} aiError={aiError} generateInterpretation={generateInterpretation} />}
  </div>;
}
function Upload({ label, file, onChange }: { label: string; file: FileState; onChange: (event: ChangeEvent<HTMLInputElement>) => void }) { return <label className="file"><span>{label}</span><strong>{file?.name ?? "Choose CSV"}</strong><input type="file" accept=".csv,text/csv" onChange={onChange} /></label>; }
function Dashboard(props: { analysis: Analysis; selected: number | null; setSelected: (value: number | null) => void; question: string; setQuestion: (value: string) => void; answer: string; ask: () => void; vendor: string; setVendor: (value: string) => void; category: string; setCategory: (value: string) => void; teach: () => void; memoryMessage: string; aiSummary: string; aiError: string; generateInterpretation: () => void }) { const { analysis } = props; const selected = props.selected === null ? null : analysis.insights[props.selected]; return <section className="dashboard"><div className="summary"><p className="eyebrow">EXECUTIVE SUMMARY</p><h2>{analysis.summary}</h2><button className="ai-button" onClick={props.generateInterpretation}>Generate AI interpretation</button>{props.aiSummary && <p className="ai-summary">{props.aiSummary}</p>}{props.aiError && <p className="ai-error">{props.aiError}</p>}<div className="metrics"><Metric label="Revenue" a={analysis.totals.revenueA} b={analysis.totals.revenueB} /><Metric label="Expenses" a={analysis.totals.expenseA} b={analysis.totals.expenseB} /><Metric label="Net result" a={analysis.totals.periodA} b={analysis.totals.periodB} /></div></div>
  {analysis.appliedMemories.length > 0 && <p className="memory-used">Memory applied: {analysis.appliedMemories.map(m => `${m.subject} → ${m.fact.replace("Classify as ", "")}`).join(", ")}.</p>}
  <div className="columns"><section><p className="eyebrow">BIGGEST CHANGES</p><div className="cards">{analysis.insights.map((insight, index) => <button className="card" key={insight.variance.category} onClick={() => props.setSelected(index)}><span>{insight.variance.category}</span><strong className={insight.variance.change >= 0 ? "positive" : "negative"}>{insight.variance.change >= 0 ? "+" : "−"}{formatMoney(Math.abs(insight.variance.change))}</strong><small>{formatPercent(insight.variance.percentChange)} · View evidence</small></button>)}</div></section>
  <section className="chat"><p className="eyebrow">ASK LEDGERLENS</p><h3>Grounded in this analysis</h3><div className="chips"><button onClick={() => props.setQuestion("Why did revenue increase?")}>Why did revenue increase?</button><button onClick={() => props.setQuestion("What is driving higher expenses?")}>What is driving higher expenses?</button></div><textarea value={props.question} onChange={e => props.setQuestion(e.target.value)} placeholder="Ask about these financial changes" /><button onClick={props.ask} disabled={!props.question.trim()}>Ask →</button>{props.answer && <p className="answer">{props.answer}</p>}</section></div>
  <section className="teach"><div><p className="eyebrow">TEACH LEDGERLENS</p><h3>Save business context for the next run</h3></div><input value={props.vendor} onChange={e => props.setVendor(e.target.value)} aria-label="Vendor" /><span>belongs under</span><input value={props.category} onChange={e => props.setCategory(e.target.value)} aria-label="Category" /><button onClick={props.teach}>Remember</button>{props.memoryMessage && <p>{props.memoryMessage}</p>}</section>
  {selected && <aside className="evidence"><button className="close" onClick={() => props.setSelected(null)}>×</button><p className="eyebrow">EVIDENCE · {selected.confidence} CONFIDENCE</p><h2>{selected.variance.category} changed {selected.variance.change >= 0 ? "+" : "−"}{formatMoney(Math.abs(selected.variance.change))}</h2><p>Period A: {formatMoney(selected.variance.periodA)} · Period B: {formatMoney(selected.variance.periodB)}</p><h3>Primary drivers</h3>{selected.drivers.map(driver => <div className="driver" key={driver.counterparty}><strong>{driver.counterparty}</strong><span>{driver.change >= 0 ? "+" : "−"}{formatMoney(Math.abs(driver.change))} · {Math.abs(driver.contributionPercent).toFixed(0)}% of change</span>{driver.transactions.map(t => <small key={t.transactionId}>{t.date} · {t.description || t.counterparty} · {formatMoney(t.amount)} · {t.sourceFile}, row {t.sourceRow}</small>)}</div>)}{!selected.drivers.length && <p>No matching transaction detail was found; this variance comes from the uploaded summary.</p>}</aside>}
  </section>; }
function Metric({ label, a, b }: { label: string; a: number; b: number }) { const change = b - a; return <div><span>{label}</span><strong>{formatMoney(b)}</strong><small className={change >= 0 ? "positive" : "negative"}>{change >= 0 ? "+" : "−"}{formatMoney(Math.abs(change))}</small></div>; }
